import prestodb

'''
A sample query using presto connected to a 
cassandra table 

'''
# Set the connection 

connection = prestodb.dbapi.connect(
    host='localhost',
    catalog='cassandra',
    user='Wayne',
    port='8090',
    schema='pinterest'
)

# Set the cursor object    
cur = connection.cursor()

# Execute the following query 
cur.execute("SELECT title, follower_count, is_image_or_video FROM pinterest_data")
rows = cur.fetchall()

# Iterate through the rows generated by the query, and print them out to the terminal 
for row in rows:
    print(row)
