import prestodb

'''
A sample query using presto connected to a 
cassandra table 

NOTE: Please start both presto and cassandra first before running the script 

PRESTO

Run the following inside the bin folder of your presto installation 

sudo ./presto --server localhost:8090 --catalog cassandra
The port number can be configured under the settings

CASSANDRA 
for Cassandra, use: 

sudo Cassandra -R 

to start the daemon 

To further check run:

nodetool status 

and sudo service cassandra status 

To check that cassandra is up 


'''
# Set the connection 

connection = prestodb.dbapi.connect(
    host='localhost',
    catalog='cassandra',
    user='Wayne',
    port='8090',
    schema='pinterest'
)

# Set the cursor object    
cur = connection.cursor()

# Execute the following query 
cur.execute("SELECT title, follower_count, is_image_or_video FROM pinterest_data")
rows = cur.fetchall()

# Iterate through the rows generated by the query, and print them out to the terminal 
for row in rows:
    print(row)
